services:
  - type: web
    name: public-api
    env: node
    buildCommand: npm run deploy
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: AWS_REGION
        value: eu-west-3
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: RABBITMQ_URL
        sync: false

databases:
  - name: postgres
    databaseName: invoice_app
    user: invoice_user
